ignore_colors = [
 [0, 0, 0, 0],
 # [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed
# r/placeDE overlay target: https://place.army/overlay_target.png
# r/ukPlace overlay target: https://placeuk.g3v.co.uk/template/ukplace

[versions]
"browser" = 20
"python" = 3
"nodejs" = 1

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "lurch"
#file = "pictures/gronkh-and-friends.png"
#startx = 160
#starty = -342
file = "pictures/gronkh-and-friends-new.png"
startx = 186
starty = -335
priority = 1

[[structure]]
name = "schildi"
file = "pictures/abenteurerdiebegegnung.png"
startx = 242
starty = -304
priority = 1

[[structure]]
name = "phunk"
file = "pictures/tattoologophunkrplace.png"
startx = 262
starty = -288
priority = 1

#[[structure]]
#name = "gronkh-2"
#file = "pictures/gronkh-2.png"
#startx = 210
#starty = -338
#priority = 1
